Nep 292 user preference
siristechnology/nepaltoday-app pull request #193
Opened 2020-11-09 13:51 UTC by ShivaAryal

-   [ ] Include Jira Ticket No. in Title
-   [ ] Write Unit Tests
-   [ ] Add screenshots whenever possible
-   [ ] Make sure Github Action build succeed
-   [ ] Address Automated Code Reviews from LGTM, Deepscan and Synk
-   [ ] Add Reviewers

2020-11-09 23:31 UTC, syuraj requested changes

2020-11-09 23:31 UTC, syuraj commented on src/services/readArticles.service.js
>  class ReadArticleService{
@ShivaAryal Please, write some tests around these services.

2020-11-09 23:31 UTC, syuraj commented on src/services/asyncStorageService.js
>              articles.push(article)
@ShivaAryal Please, write some tests around these services.

2020-11-10 04:54 UTC, merged

2020-11-10 05:39 UTC, ShivaAryal commented on src/services/readArticles.service.js
>  class ReadArticleService{
app mai code lekhne vannuvako?

2020-11-10 05:39 UTC, ShivaAryal commented on src/services/readArticles.service.js
>  class ReadArticleService{
@syuraj